### ISSUE TITLE
DOMXPath::query(): Invalid predicate

### ISSUE THREAD

**Issue by mircobabini** [Yoohoo-Plugins/pmpro-pdf-invoices#18]
[type] => 2
[message] => DOMXPath::query(): Invalid predicate
[file] => /public_html/wp-content/plugins/pmpro-pdf-invoices/includes/dompdf/src/Css/Stylesheet.php
[line] => 1006

Server: siteground
PHP: 7.2

**Comment by andrewlimaza** [comment]
I'm assuming this is fixed as we're on the latest DOMPDF build.
