### ISSUE TITLE
Some Shortcodes are not working

### ISSUE THREAD

**Issue by GCalToolkit** [Yoohoo-Plugins/pmpro-pdf-invoices#44]
I worked around this by adding at line 227 of pmpro-pdf-invoices.php to use {{pmpro_name}} instead of
pmpro_bfirstname and pmpro_blastname, which aren't implemented despite being in 2 of the templates. Too small for a PR and I'm sure you'll add something better.

`'{{pmpro_name}}' => $user->first_name . " " . $user->last_name ?: '',`

**Comment by andrewlimaza** [comment]
Thanks for this @GCalToolkit, the pmpro_bfirstname and pmpro_blastname has changed from user meta to being stored in order meta and will need to be updated accordingly.

I think it's a good idea to add in this variable, and I'll look at adding it in the next release.

**Comment by andrewlimaza** [comment]
No PR is too big or too small, I have added this in and will be including this in the next release and give you credit. Thank you for your contribution.

**Comment by andrewlimaza** [comment]
Here's the commit, this follows how PMPro does it but can be added in using a filter if you specifically need `{{pmpro_name}}` variable - https://github.com/Yoohoo-Plugins/pmpro-pdf-invoices/commit/69af3d1ff47f5281839ab59f47d450b253d42e38
